name: Update Keywords

on:
  schedule:
    - cron: "* * * * *"

jobs:
  update_keywords:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Keywords
        run: node assets/update_keywords.js


      - name: Commit and Push Changes
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "ammaryousaf341@gmail.com"
          git add .
          git commit -m "Update meta keywords"
          git push